// <auto-generated />
namespace PassengerNameListWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class passenger : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(passenger));
        
        string IMigrationMetadata.Id
        {
            get { return "201712161257371_passenger"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
